import React,{useContext} from 'react'
import './Contenu.css'
import {ThemeContext} from '../../Context/ThemeContext'
export default function Contenu() {
    const {theme} = useContext(ThemeContext)
    return (
        <div className={theme?'contenu Light':'contenu Dark'}>
            <h1>Lorem ipsum dolor sit amet.</h1>
            Lorem, ipsum dolor sit amet consectetur adipisicing elit. Pariatur rerum sint fugit ut architecto voluptas laudantium praesentium earum cumque distinctio repudiandae ipsum amet impedit rem eaque fugiat dicta, harum officiis. Blanditiis ex aperiam praesentium cumque reprehenderit iure et earum, temporibus at ipsum nulla ullam debitis! Vel quas explicabo fugit obcaecati cupiditate magnam quidem quos omnis odit repellat molestias, ut optio ipsam quaerat, est tempore voluptate aliquid nam sit ratione! Quos suscipit magnam minima aut blanditiis dicta ratione veritatis consectetur voluptatum sit iste, quod eaque debitis quam deleniti quia delectus animi minus! Culpa voluptatibus exercitationem aut mollitia assumenda libero distinctio quaerat esse odio ipsam! Atque, recusandae. Commodi amet laudantium corporis nihil nisi, unde quis explicabo, corrupti, possimus facere repellendus quasi? Quasi praesentium, cumque in, adipisci voluptatem obcaecati repudiandae magnam quos amet perspiciatis laboriosam blanditiis! Nulla nostrum, dolore harum cupiditate autem tempore perspiciatis molestias nam, blanditiis beatae deserunt hic, quam nemo ea deleniti recusandae sint doloremque veniam cum natus consectetur debitis in alias! Vel vero doloremque pariatur voluptates. Modi reiciendis officia incidunt ea unde accusamus pariatur sit, consequuntur, adipisci, odio saepe fuga. Eaque, quis quod corporis consectetur sit iste architecto quibusdam dolores. Repudiandae distinctio alias minima dolorum consectetur pariatur iure, eaque provident placeat eveniet? Possimus facere numquam illum amet autem eius provident reprehenderit praesentium, ut, nulla harum, ea veniam repudiandae ipsum rerum impedit excepturi sint molestiae accusamus. Modi porro odit, laborum omnis nihil ipsam unde aliquam eos tenetur magni soluta dolorem possimus doloribus deserunt fuga reiciendis. Molestias nesciunt ratione voluptas soluta, tenetur laboriosam in quod aperiam! Dolor eum consectetur, cupiditate cum repellendus dicta aliquam quas molestias vel odit consequuntur accusamus ullam harum expedita libero magnam, doloribus deserunt minima iure obcaecati! In at id voluptatum nostrum provident exercitationem totam odit recusandae nulla odio! Dolores voluptate labore numquam veniam praesentium sint eius pariatur enim ullam sunt at quibusdam deserunt eligendi dignissimos tenetur distinctio nobis debitis, sapiente perferendis quo sit! Ipsum officia totam velit delectus. Dicta quas enim quae molestias harum labore placeat, nesciunt velit veritatis dolorum eaque commodi! Dignissimos sed fugit in consequatur nihil aspernatur non vel commodi animi? Laudantium recusandae nam suscipit fugit.
        </div>
    )
}

